name: Test Workflow

on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      # node js configuration
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' 
          cache: 'npm' 

      # dependencies installation
      - name: Installation des dépendances
        run: npm ci